<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>WlanLivePathTester.Windows</AssemblyName>
    <RootNamespace>WlanLivePathTester.Windows</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\WlanLivePathTester.Core\WlanLivePathTester.Core.csproj" />
  </ItemGroup>
</Project>
